version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api_c1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    depends_on:
      - db
    ports:
      - '3000:3000'
    restart: always
volumes:
  pgdata:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
